version: "3.8"

services:
  migrator:
    build:
      context: ../ch-dev-config
      dockerfile: codespaces.Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host

  ch:
    build:
      context: ../ch-dev-config
      dockerfile: clickhouse.dockerfile
    network_mode: host
    restart: unless-stopped
    volumes:
      - ch_data:/var/lib/clickhouse

  zookeeper:
    network_mode: host
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"

volumes:
  ch_data: